spring.application.name=PetManagementSystem

spring.datasource.url=jdbc:mysql://localhost:3306/petManagement?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=0526
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.fotmat_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gohilparth20060317@gmail.com
spring.mail.password=mwcl ilni vxtp fwit
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key.id=rzp_test_TDlzOrtscO2d4t
razorpay.key.secret=RY0n5hn4DRKdKAH7myaHrMgX

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.jackson.deserialization.fail-on-null-for-primitives=false